---
# Default values for sample.
replicaCount: 1

image:
  repository: k8s.gcr.io/echoserver
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

pod:
  port: 8080
  health: {}
    # port: 8080
    # livePath: /
    # readyPath: /

namespaceOverride: ""
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: default

podAnnotations: {}

# this image cannot work not as root
podSecurityContext:
  runAsUser: 0

networkPolicy:
  enabled: false
  externalIpRanges: # allow from GCP nodes and LoadBalancer health ranges (for SVCNEG HeatlhChecks)
  - 10.0.0.0/8
  - 130.211.0.0/22
  - 35.191.0.0/16

svc:
  enabled: true

ingress:
  enabled: true
  version: v1  # in case GKE 1.18 or lower - it does not support v1 ingress yet - use ingress version: v1beta1
  class: "" # assume default impl, use gce-internal for GKE Internal LoadBalancer, use istio or nginx when Istio or Nginx installed

  annotations:
    # required in case GKE Ingress as it does not support both http and https on the same ip
    kubernetes.io/ingress.allow-http: "false"
    # for NGINX ingress to rewrite urls to ensure last slash is added
    nginx.ingress.kubernetes.io/rewrite-target: /
    # kubernetes.io/tls-acme: "true"
  host: echoserver.learning.minikube.testing
  tls:
    key: ""
    crt: ""

apigateway:
  enabled: false
  gateway:
    name: external
    namespace: gateways
  route:
    host: ""

anthos:
  ingress:
    enabled: false

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

affinity:
  nodeAffinity:
    enabled: false
    zones:
    - us-central1-a
    - us-central1-b
    - us-central1-c
  podAntiAffinity:
    enabled: true
    topologyKey: kubernetes.io/hostname
    # topologyKey: failure-domain.beta.kubernetes.io/zone
    # topologyKey: topology.kubernetes.io/zone
