---
- name: Clean current system
  hosts: local
  gather_facts: true
  tasks:
  - name: Clean systemd journal /var/log/journal logs
    ansible.builtin.shell:
      journalctl --vacuum-size={{ systemd_journal.max_size }} --vacuum-time={{ systemd_journal.max_duration }} --rotate
    register: journal_clean
    ignore_errors: true
    changed_when:
    - not(journal_clean.stderr is search('freed 0B'))
    - journal_clean.stdout
  - name: Debian based specific cleaning
    when: ansible_os_family == "Debian"
    block:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: "{{ update_cache_timeout }}"
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes
        force_apt_get: yes
    - name: Remove useless packages from the cache
      ansible.builtin.apt:
        autoclean: true
        force_apt_get: yes
    - name: Clean apt-get
      ansible.builtin.apt:
        clean: true
        force_apt_get: yes
    - name: Remove old kernels
      ansible.builtin.include_role:
        name: remove_old_kernels
  - name: RHEL based system specific cleaning
    when: ansible_os_family == "RedHat"
    block:
    - name: Remove dependencies that are no longer required from RHEL based system
      ansible.builtin.dnf:
        autoremove: yes
    - name: Remove useless packages from the cache from RHEL based system
      ansible.builtin.shell:
        yum clean all
      register: yum_result
      changed_when: '"0 files removed" not in yum_result.stdout'
  - name: Clean /var/log rotated logs and dist upgrade logs
    ignore_errors: true
    ansible.builtin.shell:
      find /var/log -type f -regex ".*\.gz$" -delete -print && \
      find /var/log -type f -regex ".*[-,\.][0-9]*$" -delete -print && \
      find /var/log -type f -regex ".*\.old$" -delete -print && \
      for i in `find /var/log/dist-upgrade -mindepth 1 -type d 2>/dev/null` ; do echo $i && rm -rf $i; done
    register: log_clean
    changed_when: log_clean.stdout
  - name: Clean all podman (root) and docker containers, images and volumes
    ansible.builtin.shell: |
      command -v podman 1>/dev/null 2>/dev/null && {
        PODMAN_PRUNE_OUTPUT="$(podman system prune --all --volumes --force | grep -v -e "Deleted [PCVI]" -e "Total reclaimed space: 0B")"
        if [ -n "${PODMAN_PRUNE_OUTPUT}" ]; then
          echo "${PODMAN_PRUNE_OUTPUT}"
        fi
      }
      command -v docker 1>/dev/null 2>/dev/null && {
        ITEMS=$(docker container ls --all -q)
        [ -n "${ITEMS}" ] && docker container rm ${ITEMS} --force

        DOCKER_PRUNE_OUTPUT="$(docker system prune --all --volumes --force)"
        [ "${DOCKER_PRUNE_OUTPUT}"  != "Total reclaimed space: 0B" ] && {
          echo "${DOCKER_PRUNE_OUTPUT}"
        }
      }
    register: clean_out
    changed_when: clean_out.stdout
    failed_when: false
  - name: Clean all containerd images
    ansible.builtin.shell: |
      # When minikube runs on containerd it overrding config with own, fix config to default one.
      command -v crictl 1>/dev/null 2>/dev/null && {
        CRICTL_PRUNE_OUTPUT="$(crictl rmi -a 2>&1 | grep -v 'No images to remove')"
        if [[ "${CRICTL_PRUNE_OUTPUT}" == *"unknown service"* ]]; then
          containerd config default > /etc/containerd/config.toml
          systemctl restart containerd
          while [[ "$(systemctl is-active containerd)" != "active" ]]; do
            printf "."
            sleep 1
          done
          CRICTL_PRUNE_OUTPUT="$(crictl rmi -a 2>&1 | grep -v 'No images to remove')"
        fi
        if [[ "${CRICTL_PRUNE_OUTPUT}" == *"context deadline exceeded"* ]]; then
          echo 'runtime-endpoint: unix:///var/run/containerd/containerd.sock
      image-endpoint: unix:///var/run/containerd/containerd.sock' > /etc/crictl.yaml
          CRICTL_PRUNE_OUTPUT="$(crictl rmi -a 2>&1 | grep -v 'No images to remove')"
        fi
        if [ -n "${CRICTL_PRUNE_OUTPUT}" ]; then
          echo "${CRICTL_PRUNE_OUTPUT}"
        fi
      }
    register: clean_out
    changed_when: clean_out.stdout
    failed_when: false
    args:
      executable: /bin/bash
  - become: false
    block:
    - name: Clean all podman (user) containers, images and volumes
      ansible.builtin.shell: |
        command -v podman 1>/dev/null 2>/dev/null && {
          PODMAN_PRUNE_OUTPUT="$(podman system prune --all --volumes --force |grep -v -e "Deleted [PCVI]" -e "Total reclaimed space: 0B")"
          if [ -n "${PODMAN_PRUNE_OUTPUT}" ]; then
            echo "${PODMAN_PRUNE_OUTPUT}"
          fi
        }
      register: clean_out
      changed_when: clean_out.stdout
      failed_when: false
  - become: false
    block:
    - name: Clean Terraform cached plugins
      ansible.builtin.shell: |
        TERRAFORM_PLUGINS="${HOME}/.terraform.d/plugins"
        mkdir -p "${TERRAFORM_PLUGINS}"
        command -v terraform 1>/dev/null 2>/dev/null && {
          rm -rf ${TERRAFORM_PLUGINS}/*
        }
      register: clean_out
      changed_when: clean_out.stderr
      failed_when: false
