all:
  hosts:
    localhost:
  vars:
    options:
      gke_mode: true
      gke:
        cluster_name: "shared1-dev"
        region: "us-central1"
        zone_letter: "a"
    gatekeeper:
      chart_variables:
        replicas: 1
        version: "3.17.0"
