# yamllint disable-file
# without this cnrm-system deployments failed
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "cluster-config.labels" . | nindent 4 }}
    kubernetes.io/cluster-service: "true"
  name: cnrm-psp
rules:
- apiGroups:
  - policy
  resourceNames:
  - gce.privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
# Create cluster rolebinding as cnrm-system namespace may not exist yet
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubernetes.io/description: Cnrm PSP bound to crm-system service accounts
  labels:
    {{- include "cluster-config.labels" . | nindent 4 }}
    kubernetes.io/cluster-service: "true"
  name: cnrm-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cnrm-psp
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:cnrm-system
