---
branches:
  only:
  - master
jobs:
  include:
  - stage: build
    language: java
    jdk: openjdk17
    before_script: cd java
    script: make build
    cache:
      directories:
      - $HOME/.m2
    env:
    - CACHE=java
  - language: java
    jdk: openjdk17
    before_script: cd algorithms/project-euler
    script: make build
    cache:
      directories:
      - $HOME/.m2
    env:
    - CACHE="algorithms/project-euler"
  - language: rust
    before_script: cd rust/guessing_game
    cache: cargo
  - language: go
    go: "1.17"
    before_install: cd go/learning
    script:
    - go build -mod=mod -o .  ./...
    - go test ./pkg/language
    - ./language
    cache:
      directories:
      - $HOME/.cache/go-build  # Cache the binaries
      - $HOME/gopath/pkg/mod   # Cache the Go modules
  - language: python
    python: "nightly" # contains 3.10-dev, switch to 3.10 when available https://docs.travis-ci.com/user/languages/python/ when
    before_install: cd python/apps/exchange-rate
    install:
    - pip3 install tox
    script:
    - make build
    - pip3 install .
    - exchange-rate
    cache: pip
