---
# Travis supports natively the following software on the Ubuntu 22.04
# https://docs.travis-ci.com/user/reference/jammy/#jvm-clojure-groovy-java-scala-support
dist: jammy
# branches:
#   only:
#   - main
jobs:
  include:
  - stage: build
    language: java
    jdk: openjdk17
    before_script: cd java
    # TODO bring back running via make when travis supports jdk21
    # script: make build
    script: mvn -Djava.version=17 -s .mvn/settings.xml --show-version clean install
    cache:
      directories:
      - $HOME/.m2
    env:
    - CACHE=java
  - language: java
    jdk: openjdk17 # Travis does not support java 21 yet'
    before_script: cd algorithms/project-euler
    # TODO bring back running via make when travis supports jdk21
    # script: make build
    script: mvn -Djava.version=17 -s .mvn/settings.xml --show-version clean install
    cache:
      directories:
      - $HOME/.m2
    env:
    - CACHE="algorithms/project-euler"
  - language: rust
    before_script: cd rust/guessing_game
    cache: cargo
  - language: go
    go: "1.20" # Travis does not support go 1.21 yet'
    before_install: cd go/learning
    script:
    - go build -mod=mod -o .  ./...
    - go test ./pkg/language
    - ./language
    cache:
      directories:
      - $HOME/.cache/go-build  # Cache the binaries
      - $HOME/gopath/pkg/mod   # Cache the Go modules
  - language: python
    python: "3.11"
    before_install: cd python/apps/exchange-rate
    install:
    - pip3 install tox
    script:
    - make build
    - pip3 install .
    - exchange-rate
    cache: pip
