# yamllint disable-file
---
apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: external-alb
spec:
  scheme: internet-facing
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: external-alb
spec:
  # Configures the IngressClass to use EKS Auto Mode
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: external-alb
---
apiVersion: eks.amazonaws.com/v1
kind: IngressClassParams
metadata:
  name: internal-alb
spec:
  scheme: internal
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
  name: internal-alb
spec:
  # Configures the IngressClass to use EKS Auto Mode
  controller: eks.amazonaws.com/alb
  parameters:
    apiGroup: eks.amazonaws.com
    kind: IngressClassParams
    name: internal-alb
