# yamllint disable-file
# ---
# apiVersion: karpenter.sh/v1
# kind: NodePool
# metadata:
#   name: compute-spot-amd64
# spec:
#   template:
#     spec:
#       nodeClassRef:
#         group: eks.amazonaws.com
#         kind: NodeClass
#         name: default
#       requirements:
#       - key: karpenter.sh/capacity-type
#         operator: In
#         values:
#         - spot
#       - key: eks.amazonaws.com/instance-category
#         operator: In
#         values:
#         - c
#         - m
#         - r
#       - key: kubernetes.io/arch
#         operator: In
#         values:
#         - amd64
#       - key: kubernetes.io/os
#         operator: In
#         values:
#         - linux
#   limits:
#     cpu: "100"
#     memory: 1024Gi
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: compute
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: eks.amazonaws.com/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
        - arm64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
  limits:
    cpu: "100"
    memory: 1024Gi
