# yamllint disable-file
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    {{- include "cluster-config.labels" . | nindent 4 }}
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp3
  csi.storage.k8s.io/fstype: xfs
  #TODO https://docs.aws.amazon.com/eks/latest/userguide/create-storage-class.html
  # encrypted: "true"
  # kmsKeyId: <custom-key-arn>
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: ebs-csi
  labels:
    velero.io/csi-volumesnapshot-class: "true"
driver: ebs.csi.eks.amazonaws.com
# flag does not matter as
# per
# https://github.com/vmware-tanzu/velero/blob/release-1.16/design/clean_artifacts_in_csi_flow.md
# VolumeSnapshot and VolumeSnapshotContent are deleted when Backup is created automatically either way
deletionPolicy: Retain # or Delete
