# yamllint disable-file
---
{{- $appConfig := .Files.Glob .Values.mq.appConfigPath }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  01-admin-config.mqsc: |-
{{ .Files.Get .Values.mq.adminConfigPath | indent 4}}
{{- if $appConfig }}
  02-app-config.mqsc: |-
{{ .Files.Get .Values.mq.appConfigPath | indent 4}}
{{- end }}
