# yamllint disable-file
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
stringData:
  admin-pass: {{ .Values.webconsole.admin_pass }}
  {{- if .Values.mq.app_pass }}
  app-pass: {{ .Values.mq.app_pass }}
  {{- end }}

---
{{- if .Values.mq.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-tls-secret
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{ .Release.Name }}.crt: {{ .Values.mq.tls.crt | b64enc }}
  {{ .Release.Name }}.key: {{ .Values.mq.tls.key | b64enc }}
{{- end }}
