# yamllint disable-file
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
stringData:
  admin-pass: {{ .Values.webconsole.admin_pass }}
  {{- if .Values.webconsole.app_pass }}
  app-pass: {{ .Values.webconsole.app_pass }}
  {{- end }}
