# yamllint disable-file
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ include "app.namespace" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: 1
  serviceName: mq
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default "default" }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          env:
          - name: MQ_DEV
            value: "false"
          - name: LICENSE
            value: "accept"
          - name: MQ_QMGR_NAME
            value: {{ .Release.Name | upper }}
          - name: MQ_MULTI_INSTANCE
            value: "false"
          - name: LOG_FORMAT
            value: "json"
          - name: MQ_ENABLE_METRICS
            value: "true"
          - name: DEBUG
            value: "false"
          - name: MQ_ENABLE_TRACE_STRMQM
            value: "false"
          - name: MQ_EPHEMERAL_PREFIX
            value: "/run/mqm"
          - name: MQ_ENABLE_EMBEDDED_WEB_SERVER
            value: "true"
          - name: MQ_GRACE_PERIOD
            value: "30"
          - name: MQ_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "app.fullname" . }}-secret
                key: admin-pass
          {{- if .Values.mq.app_pass }}
          - name: MQ_APP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "app.fullname" . }}-secret
                key: app-pass
          {{- end }}
          ports:
            - name: mq-manager
              containerPort: 1414
              protocol: TCP
            - name: mq-webconsole
              containerPort: 9443
              protocol: TCP
            - name: mq-metrics
              containerPort: 9157
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - chkmqready
            # tcpSocket:
            #   port: mq-manager
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: "/ibmmq/console/login.html"
              port: mq-webconsole
              scheme: HTTPS
          volumeMounts:
            - name: mqsc
              mountPath: /etc/mqm/01-admin-config.mqsc
              subPath: 01-admin-config.mqsc
            - name: mqsc
              mountPath: /etc/mqm/02-app-config.mqsc
              subPath: 02-app-config.mqsc
            {{- if .Values.mq.tls.enabled }}
            - name: mqtls
              mountPath: "/etc/mqm/pki/keys/{{ .Release.Name }}"
              readOnly: true
            {{- end }}
            - name: mqm
              mountPath: /mnt/mqm
            - name: mqm-data
              mountPath: /mnt/mqm-data
            - name: mqm-log
              mountPath: /mnt/mqm-log
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mqsc
          configMap:
            name: {{ include "app.fullname" . }}-config
        {{- if .Values.mq.tls.enabled }}
        - name: mqtls
          secret:
            secretName: {{ include "app.fullname" . }}-tls-secret
        {{- end }}
        {{- if not .Values.mq.persistence.enabled }}
        - name: mqm
          emptyDir:
            sizeLimit: {{ .Values.mq.persistence.mqm.size | default "8Gi" | quote }}
        - name: mqm-data
          emptyDir:
            sizeLimit: {{ .Values.mq.persistence.data.size | default "8Gi" | quote }}
        {{- end }}
        - name: mqm-log
          emptyDir:
            sizeLimit: {{ .Values.mq.persistence.logs.size | default "8Gi" | quote }}
  volumeClaimTemplates:
  {{- if .Values.mq.persistence.enabled }}
  - metadata:
      name: mqm
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.mq.persistence.storageClass | default nil | quote }}
      resources:
        requests:
          storage: {{ .Values.mq.persistence.mqm.size | default "8Gi" | quote }}
  - metadata:
      name: mqm-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.mq.persistence.storageClass | default nil | quote }}
      resources:
        requests:
          storage: 8Gi
  {{- end }}
