all:
  hosts:
    localhost:
  vars:
    base_host: "matihost.mooo.com"
    admin:
      port: 9901
    envoy:
      port: 4443
      tls:
        cn: "*.{{ base_host }}"
      template_config: https2many.yaml.j2
      https_target_url: github.com
      http_target_url: http.internal.testing.minikube
