---
image:
  repository: ibmcom/mq
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

namespaceOverride: ""
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: default

mq:
  configPath: "config.mqsc"

resources:
  limits:
    cpu: 2
    memory: 768Mi
    ephemeral-storage: "4Gi"
  requests:
    cpu: 200m
    memory: 384Mi
    ephemeral-storage: "2Gi"

webconsole:
  admin_pass: default
  # User app password for accessing queues is optional
  # app_pass: optional
  istio:
    enabled: false
    hostSuffix: testing.minikube
