---
image:
  repository: ibmcom/mq
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

namespaceOverride: ""
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: default

mq:
  adminConfigPath: "admin-config.mqsc"
  appConfigPath: "app-config.mqsc"
  # svcType: LoadBalancer
  # app_pass: <none>
  persistence:
    enabled: false
    # storageClass: <default>
    data:
      size: 4Gi
    mqm:
      size: 2Gi
    logs:
      size: 4Gi

resources:
  limits:
    cpu: 2
    memory: 768Mi
    ephemeral-storage: "6Gi"
  requests:
    cpu: 200m
    memory: 384Mi
    ephemeral-storage: "4Gi"

webconsole:
  admin_pass: default
  # User app password for accessing queues is optional
  istio:
    enabled: false
    hostSuffix: testing.minikube
