apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: external-jenkins
  namespace: ci
spec:
  parentRefs:
  - name: external
    namespace: gateways
  hostnames: ["jenkins.gxlb.gke.shared1.dev.gcp.testing"]
  rules:
  - backendRefs:
    - name: ci-jenkins
      namespace: ci
      port: 80
