# yamllint disable-file
#
# Helm chart config: helm show values jenkinsci/jenkins
# Current chart version: {{ chart_version }}
# Default values for jenkinsci/jenkins chart:
# helm show values jenkinsci/jenkins
namespaceOverride: ci

controller:
{% if use_prebuild_jenkins_image is sameas true %}
  image: "quay.io/matihost/jenkins"
  tag: "2.361.1"  # has to be semver compliant
  imagePullPolicy: Always
  initializeOnce: true
  installPlugins: false
{% else %}
  image: "jenkins/jenkins"
  tag: "2.361.1"
  initializeOnce: false
  installLatestPlugins: true
  installLatestSpecifiedPlugins: false
  installPlugins:
  - branch-api:2.1046.v0ca_37783ecc5
  - pipeline-stage-view:2.24
  - kubernetes:3704.va_08f0206b_95e
  - workflow-job:1232.v5a_4c994312f1
  - workflow-aggregator:590.v6a_d052e5a_a_b_5
  - cloudbees-disk-usage-simple:170.va_fd5b_4ee6858
  - credentials:1143.vb_e8b_b_ceee347
  - credentials-binding:523.vd859a_4b_122e6
  - docker-commons:1.21
  - docker-workflow:521.v1a_a_dd2073b_2e
  - git:4.11.5
  - configuration-as-code:1512.vb_79d418d5fc8
  - timestamper:1.20
  - github-branch-source:1694.vd46793a_c4a_57
  - github-oauth:0.39
  - ldap:2.12
  - google-login:1.6
  - matrix-auth:3.1.5
  - authorize-project:1.4.0
  - prometheus:2.0.11
  - simple-theme-plugin:103.va_161d09c38c7
  - jdk-tool:55.v1b_32b_6ca_f9ca
  - command-launcher:84.v4a_97f2027398
  - windows-slaves:1.8.1
{% endif %}
  servicePort: 80
  serviceType: {{ jenkins_service_type|default("NodePort") }}

  podAnnotations:
    rollme: "{{ 10000|random }}"

  ingress:
    enabled: true
    ingressClassName: {{ jenkins_ingress.class|default("nginx") }} # in case GKE: istio, gce-internal, gce-external
    apiVersion: "networking.k8s.io/{{ ingress_version }}"
    annotations:
      kubernetes.io/ingress.allow-http: "false"  ## in case GKE gce-internal class it disables HTTP
    hostName: {{ jenkins_ingress.host }}
    tls:
    - secretName: {{ jenkins_ingress.secretName }}
      hosts:
      - {{ jenkins_ingress.host }}

  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "{{ jenkins_max_cpu|default('3000m') }}"
      memory: "{{ jenkins_max_memory|default('5Gi') }}"

  sidecars:
    configAutoReload:
      enabled: true

  javaOpts: >
    -Dorg.jenkinsci.plugins.gitclient.Git.timeOut=30

  JCasC:
    enabled: true
    defaultConfig: true
    configScripts:
{% if gke_mode is sameas true %}
      environment-vars: |
        jenkins:
          globalNodeProperties:
            - envVars:
                env:
                - key: "GCP_PROJECT"
                  value: "{{ lookup('pipe', 'gcloud config get-value project') }}"
{% endif %}
      iam: |
        jenkins:
          securityRealm:
            local:
              allowsSignup: false
              enableCaptcha: false
              users:
              - id: "admin"
                name: "{{ jenkins_admin_username|default('admin') }}"
                password: "{{ jenkins_admin_pass|mandatory }}"
              - id: "user"
                name: "user"
                password: "{{ jenkins_admin_pass|mandatory }}"
      authz: |
        jenkins:
          authorizationStrategy:
            projectMatrix:
              permissions:
              - "GROUP:Job/Discover:authenticated"
              - "GROUP:Job/Read:authenticated"
              - "GROUP:Metrics/View:authenticated"
              - "GROUP:Overall/Read:authenticated"
              - "GROUP:View/Read:authenticated"
              - "USER:Agent/Build:admin"
              - "USER:Agent/Configure:admin"
              - "USER:Agent/Connect:admin"
              - "USER:Agent/Create:admin"
              - "USER:Agent/Delete:admin"
              - "USER:Agent/Disconnect:admin"
              - "USER:Agent/ExtendedRead:admin"
              - "USER:Credentials/Create:admin"
              - "USER:Credentials/Delete:admin"
              - "USER:Credentials/ManageDomains:admin"
              - "USER:Credentials/Update:admin"
              - "USER:Credentials/View:admin"
              - "USER:Job/Build:admin"
              - "USER:Job/Cancel:admin"
              - "USER:Job/Configure:admin"
              - "USER:Job/Create:admin"
              - "USER:Job/Delete:admin"
              - "USER:Job/Discover:admin"
              - "USER:Job/ExtendedRead:admin"
              - "USER:Job/Move:admin"
              - "USER:Job/Read:admin"
              - "USER:Job/Workspace:admin"
              - "USER:Metrics/HealthCheck:admin"
              - "USER:Metrics/ThreadDump:admin"
              - "USER:Metrics/View:admin"
              - "USER:Overall/Administer:admin"
              - "USER:Overall/Administer:matihost"
              - "USER:Overall/Read:admin"
              - "USER:Overall/SystemRead:admin"
              - "USER:Run/Delete:admin"
              - "USER:Run/Replay:admin"
              - "USER:Run/Update:admin"
              - "USER:SCM/Tag:admin"
              - "USER:View/Configure:admin"
              - "USER:View/Create:admin"
              - "USER:View/Delete:admin"
              - "USER:View/Read:admin"
      welcome-message: |
        jenkins:
          systemMessage: Welcome to the Matihost CI\CD server.
      script-approval: |
        security:
          scriptApproval:
            approvedSignatures:
            - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
            - "new groovy.json.JsonSlurperClassic"
      authorize-project: |
        security:
          queueItemAuthenticator:
            authenticators:
            - global:
                strategy: "triggeringUsersAuthorizationStrategy"
      neo-theme: |
        unclassified:
          simple-theme-plugin:
            elements:
              - cssUrl:
                  url: "https://tobix.github.io/jenkins-neo2-theme/dist/neo-light.css"
serviceAccount:
  name: "{{ namespace }}-jenkins"
  create: true
{% if gke_mode is sameas true %}
  annotations:
    iam.gke.io/gcp-service-account: "{{ namespace }}-jenkins@{{ lookup('pipe', 'gcloud config get-value project') }}.iam.gserviceaccount.com"
{% endif %}
serviceAccountAgent:
  name: "{{ namespace }}-agent"
  create: true
{% if gke_mode is sameas true %}
  annotations:
    iam.gke.io/gcp-service-account: "{{ namespace }}-agent@{{ lookup('pipe', 'gcloud config get-value project') }}.iam.gserviceaccount.com"
{% endif %}
agent:
  #TODO jenkins/inbound-agent mirrored image dissapeared from mirror.gcr.io
  # image: "mirror.gcr.io/jenkins/inbound-agent"
  # tag: "4.11-1"
  # image: "jenkins/inbound-agent"
  # tag: "jdk11-nanoserver-1809"
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "{{ jenkins_agent_max_cpu|default('2') }}"
      memory: "{{ jenkins_agent_max_memory|default('1Gi') }}"
persistence:
  enabled: true
  size: 16Gi
{% if gke_mode is sameas true %}
backup:
  enabled: true
  serviceAccount:
    create: false
    name: "{{ namespace }}-jenkins"
  schedule: "0 2 * * *" # at 2am
  destination: "gcs://{{ gcp_project }}-{{ namespace }}-jenkins-server-data/jenkins-backup"
  onlyJobs: true
{% endif %}
