---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: "{{ namespace }}-jenkins-backup-recover"
  name: "{{ jenkins_recover_job_name }}"
  namespace: "{{ namespace }}"
spec:
  template:
    metadata:
      labels:
        app: "{{ namespace }}-jenkins-backup-recover"
    spec:
      restartPolicy: OnFailure
      serviceAccountName: "{{ namespace }}-jenkins"
      containers:
      - name: jenkins-backup-recover
        image: maorfr/skbn
        command: ["skbn"]
        args:
        - "cp"
        - "--src"
        - "gcs://{{ gcp_project }}-{{ namespace }}-jenkins-server-data/jenkins-backup/{{ backup_id }}"
        - "--dst"
        - "k8s://{{ namespace }}/{{ namespace }}-jenkins-0/jenkins/var/jenkins_home/jobs"
        imagePullPolicy: IfNotPresent
