---
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  match:
    - excludedNamespaces:
        # k8s default ns
        - kube-system
        - default
        # gke system ns
        - application-system
        - cnrm-system
        - configconnector-operator-system
        - kalm-system
        - kube-node-lease
        - kube-public
        # my gke ns addons
        - external-dns
        - cluster-config
        # istio
        - istio-system
        - istio-ingress
        # gatekeeper
        - gatekeeper-system
        # my namespaces
        - ci
        - sample-istio
        - learning
      processes: ["*"]
  sync:
    syncOnly:
      - group: ""
        version: "v1"
        kind: "Namespace"
      - group: "networking.k8s.io"
        version: "v1"
        kind: "Ingress"
      - group: "networking.istio.io"
        version: "v1beta1"
        kind: "VirtualService"
