---
- name: Ansible basic example
  hosts: local
  gather_facts: false
  tasks:
    - name: Set initial facts
      ansible.builtin.set_fact:
        dictionaries:
          books:
            valid-k8s-name:
              title: valid k8s name
              author: matihost
            some_valid_ansible_key:
              title: Valid_ansible_key
              author: cat

    - name: Show all dictionaries
      ansible.builtin.debug:
        msg: "{{ dictionaries }}"

    - name: Set fact some_books
      ansible.builtin.set_fact:
        some_books: "{{ dictionaries.books }}"

    - name: Show books
      ansible.builtin.debug:
        msg: "{{ some_books }}"

    - name: Show all books
      ansible.builtin.include_role:
        name: show_books
      vars:
        books: "{{ some_books }}"
