clusterName: devshared1
region: northeurope
# tenant_id: ...
# oidc:
#   oidc_name: id
#   issuer_url: "https://KEYCLOAK_SERVER/realms/REALM_NAME"
#   client_id: "aro"
#   client_secret: "..."
#   username_claim: "preferred_username"
#   groups_claim:  "groups"
azure_monitor:
  forward_metrics: false
  # client_id: ....
  # client_secret: ...
  # dcr_id: ...
# secret:
#   kv: aro-kv
#   client_id: ...
#   client_secret: ...
