clusterName: devshared1
region: northeurope
# oidc:
#   oidc_name: id
#   issuer_url: "https://KEYCLOAK_SERVER/realms/REALM_NAME"
#   client_id: "aro"
#   client_secret: "..."
#   username_claim: "preferred_username"
#   groups_claim:  "groups"
