- name: Check mandatory variables
  ansible.builtin.fail:
    msg: Variable {{ item }} was not provided
  when: vars[item] is undefined
  loop:
  - jenkins_ingress
  - job
  - jenkins_admin_pass

- name: Prepare job form
  ansible.builtin.set_fact:
    job_definition: "{{ lookup('template', role_path + '/files/' + job.type + '-job.template.xml') }}"

- name: Prepare script
  ansible.builtin.set_fact:
    script_value: "{{ lookup('template', role_path + '/files/ensure-job.template.groovy') }}"


- name: Get Jenkins crump
  ansible.builtin.uri:
    url: "https://{{ jenkins_ingress.host }}//crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)"
    validate_certs: no
    force_basic_auth: yes
    user: "{{ jenkins_admin_user | default('admin') }}"
    password: "{{ jenkins_admin_pass | mandatory }}"
    method: GET
    status_code: 200
    return_content: true
  register: crump_result


- name: Ensure Job {{ job.name }} is present
  ansible.builtin.uri:
    url: https://{{ jenkins_ingress.host }}/scriptText
    validate_certs: no
    force_basic_auth: yes
    user: "{{ jenkins_admin_user | default('admin') }}"
    password: "{{ jenkins_admin_pass | mandatory }}"
    method: POST
    body_format: form-urlencoded
    body:
      script: "{{ script_value }}"
    headers:
      Jenkins-Crumb: "{{ crump_result.content.split(':')[1] }}"
      Cookie: "{{ crump_result.set_cookie }}"
    status_code: 200
    return_content: true
  register: job_result
