#cloud-config
---
repo_update: true
repo_upgrade: all

# Mezmo/LogDna configuration options
# https://github.com/logdna/logdna-agent-v2/blob/master/docs/README.md
# https://cloud.ibm.com/docs/log-analysis?topic=log-analysis-ubuntu
write_files:
  - path: /etc/logdna.env
    content: |
      MZ_INGESTION_KEY=${log_ingestion_key}
      MZ_APIHOST=api.${region}.logging.cloud.ibm.com
      MZ_LOGHOST=logs.${region}.logging.cloud.ibm.com

packages:
  - nginx
  - wget

runcmd:
  - systemctl start --now nginx
  - echo "deb https://assets.logdna.com stable main" > /etc/apt/sources.list.d/logdna.list
  - wget -qO - https://assets.logdna.com/logdna.gpg | apt-key add -
  - apt-get update
  - apt-get -y install logdna-agent
  - systemctl enable --now logdna-agent
