resource "instana_rbac_group" "admin" {
  name = "admin"

  permission_set {
    application_ids             = []
    infra_dfq_filter            = null
    kubernetes_cluster_uuids    = []
    kubernetes_namespaces_uuids = []
    mobile_app_ids              = []

    # TODO This is max per Terraform
    # permissions                 = ["CAN_CONFIGURE_AGENTS", "CAN_CONFIGURE_AGENT_RUN_MODE", "CAN_CONFIGURE_API_TOKENS", "CAN_CONFIGURE_APPLICATIONS", "CAN_CONFIGURE_APPLICATION_SMART_ALERTS", "CAN_CONFIGURE_AUTHENTICATION_METHODS", "CAN_CONFIGURE_AUTOMATION_ACTIONS", "CAN_CONFIGURE_AUTOMATION_POLICIES", "CAN_CONFIGURE_BIZOPS", "CAN_CONFIGURE_DATABASE_MANAGEMENT", "CAN_CONFIGURE_EUM_APPLICATIONS", "CAN_CONFIGURE_EVENTS_AND_ALERTS", "CAN_CONFIGURE_GLOBAL_ALERT_PAYLOAD", "CAN_CONFIGURE_GLOBAL_APPLICATION_SMART_ALERTS", "CAN_CONFIGURE_GLOBAL_INFRA_SMART_ALERTS", "CAN_CONFIGURE_GLOBAL_LOG_SMART_ALERTS", "CAN_CONFIGURE_GLOBAL_SYNTHETIC_SMART_ALERTS", "CAN_CONFIGURE_INTEGRATIONS", "CAN_CONFIGURE_LOG_MANAGEMENT", "CAN_CONFIGURE_LOG_RETENTION_PERIOD", "CAN_CONFIGURE_MAINTENANCE_WINDOWS", "CAN_CONFIGURE_MOBILE_APP_MONITORING", "CAN_CONFIGURE_MOBILE_APP_SMART_ALERTS", "CAN_CONFIGURE_PERSONAL_API_TOKENS", "CAN_CONFIGURE_RELEASES", "CAN_CONFIGURE_SERVICE_LEVEL_INDICATORS", "CAN_CONFIGURE_SERVICE_MAPPING", "CAN_CONFIGURE_SESSION_SETTINGS", "CAN_CONFIGURE_SYNTHETIC_CREDENTIALS", "CAN_CONFIGURE_SYNTHETIC_LOCATIONS", "CAN_CONFIGURE_SYNTHETIC_TESTS", "CAN_CONFIGURE_TEAMS", "CAN_CONFIGURE_USERS", "CAN_CONFIGURE_WEBSITE_SMART_ALERTS", "CAN_CREATE_HEAP_DUMP", "CAN_CREATE_PUBLIC_CUSTOM_DASHBOARDS", "CAN_CREATE_THREAD_DUMP", "CAN_DELETE_AUTOMATION_ACTION_HISTORY", "CAN_DELETE_LOGS", "CAN_EDIT_ALL_ACCESSIBLE_CUSTOM_DASHBOARDS", "CAN_INSTALL_NEW_AGENTS", "CAN_MANUALLY_CLOSE_ISSUE", "CAN_RUN_AUTOMATION_ACTIONS", "CAN_USE_SYNTHETIC_CREDENTIALS", "CAN_VIEW_ACCOUNT_AND_BILLING_INFORMATION", "CAN_VIEW_AUDIT_LOG", "CAN_VIEW_BIZOPS_ALERTS", "CAN_VIEW_BUSINESS_ACTIVITIES", "CAN_VIEW_BUSINESS_PROCESSES", "CAN_VIEW_BUSINESS_PROCESS_DETAILS", "CAN_VIEW_LOGS", "CAN_VIEW_LOG_VOLUME", "CAN_VIEW_SYNTHETIC_LOCATIONS", "CAN_VIEW_SYNTHETIC_TESTS", "CAN_VIEW_SYNTHETIC_TEST_RESULTS", "CAN_VIEW_TRACE_DETAILS"]
    # but this is max for TF provider:
    # https://github.com/instana/terraform-provider-instana/issues/20
    permissions = ["CAN_CONFIGURE_APPLICATIONS",
      "CAN_CONFIGURE_EUM_APPLICATIONS",
      "CAN_CONFIGURE_AGENTS",
      "CAN_VIEW_TRACE_DETAILS",
      "CAN_VIEW_LOGS",
      "CAN_CONFIGURE_SESSION_SETTINGS",
      "CAN_CONFIGURE_INTEGRATIONS",
      "CAN_CONFIGURE_GLOBAL_ALERT_CONFIGS",
      "CAN_CONFIGURE_GLOBAL_ALERT_PAYLOAD",
      "CAN_CONFIGURE_MOBILE_APP_MONITORING",
      "CAN_CONFIGURE_API_TOKENS",
      "CAN_CONFIGURE_SERVICE_LEVEL_INDICATORS",
      "CAN_CONFIGURE_AUTHENTICATION_METHODS",
      "CAN_CONFIGURE_RELEASES",
      "CAN_VIEW_AUDIT_LOG",
      "CAN_CONFIGURE_CUSTOM_ALERTS",
      "CAN_CONFIGURE_AGENT_RUN_MODE",
      "CAN_CONFIGURE_SERVICE_MAPPING",
      "CAN_EDIT_ALL_ACCESSIBLE_CUSTOM_DASHBOARDS",
      "CAN_CONFIGURE_USERS",
      "CAN_INSTALL_NEW_AGENTS",
      "CAN_CONFIGURE_TEAMS",
      "CAN_CREATE_PUBLIC_CUSTOM_DASHBOARDS",
      "CAN_CONFIGURE_LOG_MANAGEMENT",
      "CAN_VIEW_ACCOUNT_AND_BILLING_INFORMATION",
    ]
    website_ids = []
  }
}

output "admin_id" {
  value = instana_rbac_group.admin.id
}

resource "instana_custom_dashboard" "environment_dashboard" {
  title = "Environment :: ${local.prefix}"
  widgets = templatefile("${path.module}/config/env.dashboard.json.tpl", {
    env    = var.env,
    region = var.region
    }
  )

  access_rule {
    access_type   = "READ_WRITE"
    related_id    = instana_rbac_group.admin.id
    relation_type = "TEAM"
  }
  access_rule {
    access_type   = "READ_WRITE"
    related_id    = "-1" # Owner build in group
    relation_type = "TEAM"
  }
  access_rule {
    access_type   = "READ"
    related_id    = null
    relation_type = "GLOBAL"
  }
}


resource "instana_alerting_channel" "email" {
  name = "email"

  email {
    emails = [var.instana_admin_email]
  }
}
