gke_mode: true
gke:
  region: "us-central1"
  zone_letter: "a"
jenkins_service_type: ClusterIP
jenkins_ingress:
  host: jenkins.ci.internal.gke.shared1.dev.gcp.testing
  class: istio
  secretName: internal-wildcard-gateway-tls  # in case of ingress class istio this secret has to already be present in istio-system namespace
jenkins_jobs:
- name: learning
  description: Learning Multibranch Pipeline
  type: multibranch
  git:
    scm: https://github.com/matihost/learning.git
    jenkinsfile: Jenkinsfile
- name: ansible-image
  description: Ansible Image Build
  type: multibranch
  git:
    scm: https://github.com/matihost/learning.git
    jenkinsfile: k8s/images/ansible/Jenkinsfile
- name: learning-github
  description: Learning GitHub Pipeline
  type: github
  github:
    owner: matihost
    projects:
      include: '*'
      exclude: 'bento'
