apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-cronjob
spec:
  schedule: "*/1 * * * *"  # every 1 minute
  concurrencyPolicy: "Forbid"      # max 1 job at a time, skip next if running
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 0          # do NOT retry on failure
      template:
        spec:
          restartPolicy: Never  # recommended with backoffLimit=0
          containers:
          - name: bash-runner
            image: busybox
            command:
            - /bin/sh
            - -c
            - |
              echo "Starting job.. sleeping for 30s..."
              sleep 30
              echo "DONE"
