---
- hosts: localhost
  become: false
  vars:
    files: "{{ playbook_dir }}/files"
  tasks:

  - name: Deploy Github Actions Runner Controller Helm chart with version {{ arc.chart_version }}
    kubernetes.core.helm:
      name: "arc"
      chart_ref: "oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller"
      chart_version: "{{ arc.chart_version }}"
      release_namespace: "arc-systems"
      create_namespace: true
      wait: true
      wait_timeout: "5m0s"
      values: "{{ lookup('template', '{{ files }}/arc_helm.yaml.j2') | from_yaml }}"

  - name: Ensure {{ runner.namespace | mandatory }} dependencies are in place
    kubernetes.core.k8s:
      state: present
      definition: "{{ lookup('template', '{{ files }}/prerequisites.yaml.j2') }}"
      validate:
        fail_on_error: true
        strict: true

  - name: Deploy Runner Scale Set via Helm chart with version {{ arc.chart_version }}
    kubernetes.core.helm:
      name: "{{ runner.name | mandatory | replace('/','-') }}"
      chart_ref: "oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set"
      chart_version: "{{ arc.chart_version }}"
      release_namespace: "{{ runner.namespace | mandatory }}"
      create_namespace: false
      wait: true
      wait_timeout: "5m0s"
      values: "{{ lookup('template', '{{ files }}/arc_config.yaml.j2') | from_yaml }}"
