all:
  hosts:
    localhost:
  vars:
    options:
      gke_mode: true
      gke:
        cluster_name: "shared1-dev"
        region: "us-central1"
        zone_letter: "a"
    cert_manager:
      chart_version: "v1.11.0"
    arc:
      chart_version: "0.23.0"
    runner:
      min_replicas: 1
      storage_class: "csi-pd-rwo-xfs"
    repo:
      name: "matihost/monorepo"
      ci_namespace: "matihost-monorepo-ci"
