#usage: ansible-playbook update-okd-vms.yaml -v
---
- hosts: okd
  remote_user: student
  become: yes
  tasks:
  - name: stop all origin services
    systemd:
      name: origin*
      state: stopped
    tags:
    - origin
  - name: update packages
    yum:
      name: '*'
      state: latest
  - name: start all origin services again
    systemd:
      name: origin*
      state: started
      # has to be async, b/c from time to time task fail reporting service doesn't start, but it is a matter of time
      no_block: true
    tags:
    - origin
  - name: pause 60 seconds
    pause:
      seconds: 60
  - name: make sure all origin services are started
    systemd:
      name: origin*
      state: started
      no_block: true
    tags:
    - origin
