apiVersion: v1
baseDomain: dev.gcp.testing
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    gcp:
      type: e2-standard-4
      zones:
      - us-east1-b
      - us-east1-c
      osDisk:
        # can be only pd-ssd for control planes and free tier has a limit of 500 GB
        diskType: pd-ssd
        diskSizeGB: 128
        # encryptionKey:
        #   kmsKey:
        #     name: os-key
        #     keyRing: okd-machine-keys
        #     location: global
        #     projectID: "$(gcloud config get project)"
      tags:
      - "control-plane-${CLUSTER_NAME}"
  replicas: 1
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    gcp:
      type: e2-standard-4
      zones:
      - us-east1-b
      - us-east1-c
      osDisk:
        diskType: pd-standard
        diskSizeGB: 128
        # encryptionKey:
        #   kmsKey:
        #     name: os-key
        #     keyRing: okd-machine-keys
        #     location: global
        #     projectID: "$(gcloud config get project)"
      tags:
      - "compute-${CLUSTER_NAME}"
  replicas: 2
metadata:
  name: "${CLUSTER_NAME}"
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  # nodes network, must match VPC subnet platform.gcp.controlPlaneSubnet and platform.gcp.computeSubnet
  machineNetwork:
  - cidr: 10.14.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  gcp:
    projectID: "$(gcloud config get project)"
    region: us-east1
    defaultMachinePlatform:
      tags:
      - global-tag1
      - global-tag2
    network: private-vpc
    controlPlaneSubnet: private-subnet-us-east1
    computeSubnet: private-subnet-us-east1
## The pull secret that provides components in the cluster access to images for OpenShift components.
# a fake value to satisfy the installer. Images for okd need no subscription
pullSecret: '{\"auths\":{\"fake\":{\"auth\":\"aWQ6cGFzcwo=\"}}}'
sshKey: "$(cat ~/.ssh/id_rsa.pub)"
publish: Internal
