all:
  hosts:
    localhost:
  vars:
    operator:
      hub: "gcr.io/istio-release"
      tag: "1.12.0"
    ingress_gateway:
      max_pods: 20
      enable_node_selector: true
      default_dns_suffix: "internal.gke.{{ options.gke.cluster_name|replace('-','.') }}.gcp.testing"
      serviceAnnotations:
        cloud.google.com/load-balancer-type: Internal
        networking.gke.io/internal-load-balancer-allow-global-access: "true"
        external-dns.alpha.kubernetes.io/hostname: "*.internal.gke.{{ options.gke.cluster_name|replace('-','.') }}.gcp.testing."
      # virtual_services:
      # - name: kalm
      #   namespace: istio-system
      #   svc:
      #     port: 443
      #     fqdn: kalm-controller-manager-service.kalm-system.svc.cluster.local
    ingress_external_gateway:
      enable: true
      service_type: ClusterIP
      enable_node_selector: true
      # points Global HTTPS LB tp DNS entry  "*.external.shared1.dev.gke.testing."
      default_dns_suffix: "external.gke.{{ options.gke.cluster_name|replace('-','.') }}.gcp.testing"
      serviceAnnotations:
        # NEG name is supported in GKE version 1.18.10-gke.600 and later
        cloud.google.com/neg: '{"exposed_ports":{
                "15021":{"name": "neg-istio-external-status"},
                "80":{"name": "neg-istio-external-http"},
                "443":{"name": "neg-istio-external-https"},
                "15443":{"name": "neg-istio-external-tls"}
            }
          }'
    ingress_class:
      enable: true
      default: false
    egress_gateway:
      enable: true
    options:
      gke_mode: true
      gke:
        cluster_name: "shared1-dev"
        region: "us-central1"
        zone_letter: "a"
