#!/usr/bin/env bash

function usage() {
  echo -e "Usage: $(basename "${0}") <cluster-name> [-z zone]

Scale the GKE cluster main pool nodes to 0 - GKE management fee, storage, networks and other GCP service are still charged.
"
}

while [[ "$#" -gt 0 ]]; do
  case $1 in
  -h | --help | help)
    usage
    exit 1
    ;;
  -z)
    GCP_ZONE="$2"
    shift
    ;;
  *) PARAMS+=("$1") ;; # save it in an array for later
  esac
  shift
done
set -- "${PARAMS[@]}" # restore positional parameters

if [[ -z "${PARAMS[0]}" ]]; then
  usage
  exit 1
fi

CLUSTER_NAME=${PARAMS[0]}
GCP_ZONE="${GCP_ZONE:-$(gcloud config get-value compute/zone)}"

gcloud container clusters resize "${CLUSTER_NAME}" --num-nodes=0 --zone "${GCP_ZONE}" --quiet &&
  echo -n "The cluster ${CLUSTER_NAME} has been scaled to 0 nodes
GKE management fee, storage, networks and other GCP service are still charged."
