# yamllint disable-file
---
apiVersion: v1
data:
  ClientID: {{ .Values.secret.client_id | b64enc }}
  ClientSecret: {{ .Values.secret.client_secret | b64enc }}
kind: Secret
metadata:
  name: azure-secret-sp
  namespace: external-secrets-operator
  labels:
    {{- include "cluster-config.labels" . | nindent 4 }}
type: Opaque
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-store-spn-secret
spec:
  provider:
    azurekv:
      # Azure tenant ID, see: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
      tenantId: {{ .Values.tenant_id | quote }}
      # URL of your Key Vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "https://{{ .Values.secret.kv }}.vault.azure.net"
      authSecretRef:
        # Reference to Kubernetes Secret name containing the Service Principal client ID under the key `ClientID`
        clientId:
          name: azure-secret-sp
          namespace: external-secrets-operator
          key: ClientID
        # Reference to Kubernetes Secret name containing the Service Principal client secret under the key `ClientSecret`
        clientSecret:
          name: azure-secret-sp
          namespace: external-secrets-operator
          key: ClientSecret
