# yamllint disable-file
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: block-csi-xfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    {{- include "cluster-config.labels" . | nindent 4 }}
parameters:
  skuname: Premium_LRS
  csi.storage.k8s.io/fstype: xfs
provisioner: disk.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
