# yamllint disable-file
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    {{- include "cluster-config.labels" . | nindent 4 }}
  name: csi-pd-rwo-xfs
parameters:
  type: pd-balanced
  csi.storage.k8s.io/fstype: xfs
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  labels:
    {{- include "cluster-config.labels" . | nindent 4 }}
  name: csi-standard-rwo-xfs
parameters:
  type: pd-standard
  csi.storage.k8s.io/fstype: xfs
provisioner: pd.csi.storage.gke.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
