all:
  hosts:
    localhost:
  vars:
    cert_manager:
      chart_version: "v1.11.0"
    arc:
      chart_version: "0.22.0"
    runner:
      min_replicas: 1
      storage_class: "csi-hostpath-sc"
    repo:
      name: "matihost/monorepo"
      ci_namespace: "matihost-monorepo-ci"
