FROM python:3.11
RUN pip3 install --no-cache-dir --upgrade pip && apt-get update && apt-get install -y python3-venv && \
    pip3 install ansible openshift pipenv tox pylint pytest pre-commit ansible-lint --no-cache-dir --upgrade && \
    ansible-galaxy collection install community.kubernetes
# for python libraries needed own virtual env
ENV PATH=${PATH}:/root/.venv/user/bin
RUN python3 -m venv /root/.venv/user
