# yamllint disable-file
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: app-store
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "namespace-config.labels" . | nindent 4 }}
spec:
  provider:
    azurekv:
      # PublicCloud, USGovernmentCloud, ChinaCloud, GermanCloud
      environmentType: PublicCloud # default
      authType: WorkloadIdentity
      vaultUrl: {{ .Values.vault.url | quote }}
      serviceAccountRef:
        name: app
        namespace: {{ .Values.namespace }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: all-secrets
  namespace: {{ .Values.namespace }}
  labels:
  {{- include "namespace-config.labels" . | nindent 4 }}
spec:
  refreshInterval: 15m # 1h # rate External Secret Operator pulls Azure Key Vault
  secretStoreRef:
    kind: SecretStore
    name: app-store # name of the SecretStore
  target:
    name: all-secrets # name of the k8s Secret to be created
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
  - find:
      name:
        regexp: ".*"
