---
- hosts: localhost
  become: false
  collections:
  - kubernetes.core
  - community.general
  vars:
    files: "{{ playbook_dir }}/files"
  tasks:
  - name: Deploy Cert Manager Helm chart with version {{ cert_manager.chart_version }}
    helm:
      name: "cert-manager"
      chart_ref: "jetstack/cert-manager"
      chart_version: "{{ cert_manager.chart_version }}"
      release_namespace: "cert-manager"
      create_namespace: true
      wait: true
      wait_timeout: "5m0s"
      values: "{{ lookup('template', '{{ files }}/cert_manager_helm.yaml.j2') | from_yaml }}"

  - name: Deploy Github Actions Runner Controller Helm chart with version {{ arc.chart_version }}
    helm:
      name: "actions-runner-controller"
      chart_ref: "actions-runner-controller/actions-runner-controller"
      chart_version: "{{ arc.chart_version }}"
      release_namespace: "actions-runner-system"
      create_namespace: true
      wait: true
      wait_timeout: "5m0s"
      values: "{{ lookup('template', '{{ files }}/arc_helm.yaml.j2') | from_yaml }}"


  - name: Ensure {{ repo.ci_namespace | mandatory }} namespace present
    k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: "{{ repo.ci_namespace | mandatory }}"
          labels:
            # Ensure Istio does not inject sidecar to runner delegated jobs as they crash automatically
            #  ##[debug]Using image 'maven:3-eclipse-temurin-21' for job image
            #  ##[debug]Job pod created, waiting for it to come online matihost-monorepo-8blcq-87ffq-workflow
            #  ##[debug]Job pod is ready for traffic
            #  ##[debug]{"message":"command terminated with non-zero exit code: Error executing in Docker Container: 1","details":{"causes":[{"reason":"ExitCode","message":"1"}]}}
            istio-injection: disabled

  - name: Ensure Github Actions Runner Controller Config present
    k8s:
      state: present
      definition: "{{ lookup('template', '{{ files }}/arc_config.yaml.j2') }}"
