---
name: 'CI :: Java'
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'java/**'
  pull_request:
    branches:
      - master
    paths:
      - 'java/**'

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  checks: write
  contents: write

jobs:
  java-ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build Java source code
        run: cd java && make build
      - name: Archive app jars artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-jars
          path: java/apps/**/target/*.jar
          retention-days: 2
