---
name: 'CI :: Kaniko'
on:
  # push:
  #   # paths: "k8s/images/*"
  #   branches:
  #   - main
  #   - feature/*
  # pull_request:
  #   # paths: "k8s/images/*"
  #   branches:
  #   - main
  #   - feature/*
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner type'
        required: true
        default: 'ubuntu-22.04'
        type: choice
        options:
        - ubuntu-22.04
        - matihost
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  actions: read
  contents: read
concurrency:
  group: kaniko-${{ github.ref }}
  cancel-in-progress: true
env:
  IMAGE_TAG: "${{ github.ref == 'refs/heads/main' && 'latest' || github.sha }}"
  ROOT_IMAGE_TAG: "${{ github.ref == 'refs/heads/main' && 'root' || format('root-{0}', github.sha) }}"
jobs:
  images:
    runs-on: 'ubuntu-22.04'
    container:
      image: maven:3-eclipse-temurin-21
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Build Ansible image on GH hosted runner
      uses: aevea/action-kaniko@master
      with:
        registry: ${{ vars.REGISTRY }}
        image: matihost/ansible
        tag: "${{ env.IMAGE_TAG }}"
        username: "${{ secrets.REGISTRY_USER }}"
        password: "${{ secrets.REGISTRY_PASSWORD }}"
        path: k8s/images/ansible
        build_file: Dockerfile
        cache: true
        debug: true
    - name: Build Ansible root image on GH hosted runner
      uses: aevea/action-kaniko@master
      with:
        registry: ${{ vars.REGISTRY }}
        image: matihost/ansible
        tag: "${{ env.ROOT_IMAGE_TAG }}"
        username: "${{ secrets.REGISTRY_USER }}"
        password: "${{ secrets.REGISTRY_PASSWORD }}"
        path: k8s/images/ansible
        build_file: Dockerfile.root
        cache: true
        debug: true
