---
name: 'CI :: SelfHosted Test'
on:
  workflow_dispatch:
    # Inputs are only available for workflow_dispatch - the default is not available for other type of triggers
    # https://dev.to/mrmike/github-action-handling-input-default-value-5f2g
    inputs:
      runner:
        description: 'Runner type'
        required: true
        default: 'ubuntu-22.04'
        type: choice
        options:
          - ubuntu-22.04
          - matihost/monorepo

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
permissions:
  contents: read

jobs:
  java-ci:
    runs-on: ${{ inputs.runner }}
    container:
      image: maven:3-openjdk-17
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          # TODO reading from MAVEN_CONFIG env did not work here
          path: "/root/.m2/repository"
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build Java source code
        run: cd java && mvn -s .mvn/settings.xml --show-version clean install
      - name: Archive app jars artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-jars
          path: java/apps/**/target/*.jar
          retention-days: 2
  go:
    runs-on: ${{ inputs.runner }}
    container: golang:1.19
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |-
            ${{ github.workspace }}/.cache/go-build
            ${{ github.workspace }}/gopath/pkg/mod
          key: "${{ runner.os }}-path"
      - name: Build Java source code
        run: cd go/learning && go build -mod=mod -o . ./... && go test ./pkg/language && ./language
