---
name: 'CI :: SelfHosted Test'
on:
  workflow_dispatch:

# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
# permissions:
#   contents: read

jobs:
  java-ci:
    runs-on: self-hosted
    container:
      image: maven:3-openjdk-17
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Test
        run: pwd && ls -la
